AWSTemplateFormatVersion: 2010-09-09

Description:

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair to enable ssh access to the Windows instance
    Type: AWS::EC2::KeyPair::KeyName
  
  VPC:
    Description: VPC to deploy resources into.
    Type: 'AWS::EC2::VPC::Id'
  
  Subnet:
    Description: Subnet to deploy resources into.
    Type: 'AWS::EC2::Subnet::Id'

  SecurityGroupIds:
    Description: Specify the security group/s for resources.
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  
  LatestWindowsAmiId:
    Description: A string-based resource path representing the latest Windows Amazon Machine Image (AMI) that should be used to create the remove instance
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  WindowsInstanceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  WindowsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: 'AWS::IAM::Policy'
    DeletionPolicy: Delete
    Properties:
      PolicyName: !Sub 'Windows-client-{StackName}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
      Roles:
        - !Ref WindowsInstanceRole

  WindowsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      IamInstanceProfile: !Ref WindowsInstanceProfile
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance

Outputs:
  WindowsInstance:
    Description: Private IP address of the newly created Windows EC2 instance
    Value: !GetAtt
      - LWindowsInstance
      - PrivateIp